# Generated by Django 5.2.6 on 2025-09-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('specimen_type', models.CharField(max_length=50)),
                ('organism', models.CharField(max_length=100)),
                ('antibiotic', models.CharField(max_length=100)),
                ('ast_result', models.CharField(max_length=1)),
                ('test_date', models.DateField()),
                ('host_type', models.CharField(max_length=20)),
                ('facility', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
