# Generated by Django 5.2.6 on 2025-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='patient_type',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
