# Generated by Django 5.2.6 on 2025-09-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_api', '0002_labresult_patient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='animal_species',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='environment_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='facility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='host_type',
            field=models.CharField(choices=[('HUMAN', 'HUMAN'), ('ANIMAL', 'ANIMAL'), ('ENVIRONMENT', 'ENVIRONMENT')], default='HUMAN', max_length=20),
        ),
    ]
