# Generated by Django 5.2.6 on 2025-09-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_api', '0003_labresult_animal_species_labresult_environment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='labresult',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='animal_species',
            field=models.CharField(blank=True, choices=[('CATTLE', 'Cattle'), ('POULTRY', 'Poultry'), ('GOATS', 'Goats')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='antibiotic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='ast_result',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('I', 'I'), ('R', 'R')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='environment_type',
            field=models.CharField(blank=True, choices=[('SOIL', 'Soil'), ('WATER', 'Water'), ('AIR', 'Air'), ('WOUND', 'Wound'), ('SPUTUM', 'Sputum'), ('STOOL', 'Stool'), ('URINE', 'Urine'), ('BLOOD', 'Blood')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='facility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='host_type',
            field=models.CharField(choices=[('HUMAN', 'Human'), ('ANIMAL', 'Animal'), ('ENVIRONMENT', 'Environment')], default='HUMAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='patient_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='patient_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
