# Generated by Django 4.2.24 on 2025-09-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=64, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('specimen_type', models.CharField(blank=True, max_length=64, null=True)),
                ('organism', models.CharField(blank=True, max_length=128, null=True)),
                ('antibiotic', models.CharField(blank=True, max_length=128, null=True)),
                ('ast_result', models.CharField(blank=True, max_length=1, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('facility', models.CharField(blank=True, max_length=128, null=True)),
                ('host_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
            },
        ),
        migrations.AddConstraint(
            model_name='labresult',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 0), ('age__isnull', True), _connector='OR'), name='labresult_age_nonnegative'),
        ),
    ]
