# Generated by Django 5.2.4 on 2025-07-29 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=45)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('collection_date', models.DateField(default=datetime.date(2025, 1, 1))),
                ('specimen_type', models.CharField(max_length=100)),
                ('organism_isolated', models.CharField(max_length=100)),
                ('antibiotic_tested', models.CharField(max_length=100)),
                ('susceptibility', models.CharField(choices=[('Resistant', 'Resistant'), ('Intermediate', 'Intermediate'), ('Susceptible', 'Susceptible')], default='Resistant', max_length=20)),
                ('method', models.CharField(default='Disk diffusion', max_length=50)),
                ('laboratory', models.CharField(default='MPILO', max_length=100)),
                ('facility_location', models.CharField(default='Bulawayo', max_length=100)),
            ],
        ),
    ]
