# Generated by Django 5.2.4 on 2025-08-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labresult',
            old_name='antibiotic_tested',
            new_name='antibiotic',
        ),
        migrations.RenameField(
            model_name='labresult',
            old_name='organism_isolated',
            new_name='organism',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='collection_date',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='facility_location',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='method',
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='susceptibility',
        ),
        migrations.AddField(
            model_name='labresult',
            name='ast_result',
            field=models.CharField(choices=[('S', 'Susceptible'), ('I', 'Intermediate'), ('R', 'Resistant')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='labresult',
            name='test_date',
            field=models.DateField(default='2025-07-01'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='patient_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
