# Generated by Django 4.2.24 on 2025-09-07 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amr_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labresult',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='labresult',
            name='labresult_age_nonnegative',
        ),
        migrations.AddField(
            model_name='labresult',
            name='animal_species',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='patient_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='antibiotic',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='ast_result',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('I', 'I'), ('R', 'R')], db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='facility',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='host_type',
            field=models.CharField(blank=True, choices=[('HUMAN', 'HUMAN'), ('ANIMAL', 'ANIMAL'), ('ENVIRONMENT', 'ENVIRONMENT')], db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='organism',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='patient_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='specimen_type',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['organism', 'antibiotic'], name='amr_reports_organis_82e014_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['facility', 'test_date'], name='amr_reports_facilit_8dcd44_idx'),
        ),
    ]
