# Generated by Django 4.2.24 on 2025-09-07 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amr_reports', '0002_alter_labresult_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='created_at',
        ),
        migrations.AddField(
            model_name='labresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labresults', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='ast_result',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='host_type',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
