# Generated by Django 5.2.4 on 2025-08-26 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amr_reports', '0002_rename_antibiotic_tested_labresult_antibiotic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='labresult',
            name='host_type',
            field=models.CharField(choices=[('human', 'Human'), ('animal', 'Animal'), ('environment', 'Environment')], default='human', max_length=16),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='labresult',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='amr_reports.facility'),
        ),
    ]
